[workspace]
members = ["data", "protocol", "ser", "ser_macro"]
resolver = "2"

[workspace.package]
authors = ["hayanesuru"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hayanesuru/minecraft"
edition = "2021"

[workspace.dependencies]
mser = { path = "ser", version = "2.1.0-rc.0", default-features = false }
mser_macro = { path = "ser_macro", version = "2.1.0-rc.0", default-features = false }
minecraft_data = { path = "data", version = "2.1.0-rc.1", default-features = false }
