[package]
name = "haya_palette"
version = "0.1.0"
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
minecraft_data.workspace = true
mser.workspace = true
