[package]
name = "haya_nbt"
version = "0.1.0"
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
mser = { workspace = true }
unicode_names2 = "2"
itoa = "1"
ryu = "1"
