[package]
name = "haya_math"
version = "0.1.0"
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
libm = "0"
mser = { workspace = true }
