[package]
name = "haya_mutf8"
version = "0.1.0"
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
mser = { workspace = true }
haya_str = { workspace = true }
